name: windows-build-steps
runs:
  using: composite
  steps:
  - name: Add msbuild to PATH
    uses: microsoft/setup-msbuild@v1.3.1
  - name: Set up lz4
    run: |-
      git clone https://github.com/Microsoft/vcpkg.git
      cd vcpkg
      bootstrap-vcpkg.sh
      vcpkg integrate install
      vcpkg.exe install lz4
      vcpkg.exe install zstd
    shell: pwsh
  - name: Custom steps
    env:
      THIRDPARTY_HOME: ${{ github.workspace }}/thirdparty
      CMAKE_HOME: C:/Program Files/CMake
      CMAKE_BIN: C:/Program Files/CMake/bin/cmake.exe
      CTEST_BIN: C:/Program Files/CMake/bin/ctest.exe
      JAVA_HOME: C:/Program Files/BellSoft/LibericaJDK-8
      LZ4_HOME: ${{ github.workspace }}/vcpkg/installed/x64-windows
      LZ4_INCLUDE: ${{ github.workspace }}/vcpkg/installed/x64-windows/include
      LZ4_LIB_RELEASE: ${{ github.workspace }}/vcpkg/installed/x64-windows/lib/lz4.lib
      ZSTD_HOME: ${{ github.workspace }}/vcpkg/installed/x64-windows
      ZSTD_INCLUDE: ${{ github.workspace }}/vcpkg/installed/x64-windows/include
      ZSTD_LIB_RELEASE: ${{ github.workspace }}/vcpkg/installed/x64-windows/lib/zstd.lib
    run: |-
      # NOTE: if ... Exit $LASTEXITCODE lines needed to exit and report failure
      echo "===================== Install Dependencies ====================="      
      echo "==========  Installing JDK..."
      choco install liberica8jdk -y
      if(!$?) { Exit $LASTEXITCODE }
      mkdir $Env:THIRDPARTY_HOME
      cd $Env:THIRDPARTY_HOME
      
      echo ======================== Build RocksDB =========================
      cd ${{ github.workspace }}
      $env:Path = $env:JAVA_HOME + ";" + $env:Path
      mkdir build
      cd build
      & cmake -G "$Env:CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE=Release -DOPTDBG=1 -DPORTABLE="$Env:CMAKE_PORTABLE" -DSNAPPY=0 -DLZ4=1 -DZSTD=1 -DJNI=1 ..
      if(!$?) { Exit $LASTEXITCODE }
      cd ..
      echo "Building with VS version: $Env:CMAKE_GENERATOR"
      msbuild build/rocksdb.sln -maxCpuCount -property:Configuration=Release -property:Platform=x64
      if(!$?) { Exit $LASTEXITCODE }
    shell: pwsh
