name: post-steps
description: Steps that are taken after a RocksDB job
inputs:
  artifact-prefix:
    description: Prefix to append to the name of artifacts that are uploaded
    required: true
    default: "${{ github.job }}"
runs:
  using: composite
  steps:
  - name: java files
    uses: actions/upload-artifact@v4.0.0
    with:
      name: "${{ inputs.artifact-prefix }}-java-files"
      path: "java/target/**"
      if-no-files-found: ignore
